spring:
  application:
    name: ms-eureka-server
  security:
    user:
      name: user
      password: Aa123456

eureka:
  client:
#    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://user:Aa123456@peer1:9000/eureka/, http://user:Aa123456@peer2:9001/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    org.springframework.security: DEBUG

---
server:
  port: 9000
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

---
server:
  port: 9001
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
    prefer-ip-address: true
    instance-id: ${spring.application.name}@${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}